declare module "swiper/css";
declare module "swiper/css/pagination";
declare module "swiper/css/navigation";
declare module "swiper/css/thumbs";
declare module "react-image-gallery";
declare module "leaflet";
declare module "https://cdn.esm.sh/react-leaflet/TileLayer";
declare module "https://cdn.esm.sh/react-leaflet/MapContainer";
declare module "https://cdn.esm.sh/react-leaflet/Marker";
declare module "react-input-mask";
// declare module "@mui/icons-material/ExpandMore";
